"""Pull request creation."""

import asyncio
import logging
from pathlib import Path

from ci_guardian.config import get_settings

logger = logging.getLogger(__name__)


async def create_fix_pr(
    repo_path: Path,
    repo_full_name: str,
    run_id: int,
    fix_description: str,
    original_branch: str,
) -> str:
    """
    Create a pull request with the fix.

    Args:
        repo_path: Path to the repository with fixes applied
        repo_full_name: Repository in owner/repo format
        run_id: The original workflow run ID
        fix_description: Description of what was fixed
        original_branch: The branch that had the failure

    Returns:
        The URL of the created pull request
    """
    settings = get_settings()

    fix_branch = f"ci-guardian/fix-{run_id}"

    env = {
        "GH_TOKEN": settings.github_token,
        "PATH": "/usr/bin:/usr/local/bin",
    }

    # Create and checkout new branch
    await _run_git_command(repo_path, ["checkout", "-b", fix_branch])

    # Stage all changes
    await _run_git_command(repo_path, ["add", "-A"])

    # Commit changes
    commit_message = f"""fix: Auto-fix CI failure from run #{run_id}

{fix_description}

This fix was automatically generated by CI Guardian.
Original failure: https://github.com/{repo_full_name}/actions/runs/{run_id}
"""
    await _run_git_command(repo_path, ["commit", "-m", commit_message])

    # Push the branch
    push_url = f"https://x-access-token:{settings.github_token}@github.com/{repo_full_name}.git"
    await _run_git_command(repo_path, ["push", push_url, fix_branch], env=env)

    # Create PR using gh CLI
    pr_title = f"fix: Auto-fix CI failure from run #{run_id}"
    pr_body = f"""## Automated Fix

This pull request was automatically generated by CI Guardian to fix a CI failure.

### What was fixed

{fix_description}

### Original Failure

- **Run ID**: {run_id}
- **Run URL**: https://github.com/{repo_full_name}/actions/runs/{run_id}
- **Branch**: `{original_branch}`

---
*Generated by [CI Guardian](https://github.com/gorgeguy/ci-guardian)*
"""

    create_cmd = [
        "gh",
        "pr",
        "create",
        "--repo",
        repo_full_name,
        "--title",
        pr_title,
        "--body",
        pr_body,
        "--base",
        original_branch,
        "--head",
        fix_branch,
    ]

    process = await asyncio.create_subprocess_exec(
        *create_cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=repo_path,
        env=env,
    )

    stdout, stderr = await process.communicate()

    if process.returncode != 0:
        error_msg = stderr.decode("utf-8", errors="replace")
        logger.error(f"Failed to create PR: {error_msg}")
        raise RuntimeError(f"Failed to create PR: {error_msg}")

    pr_url = stdout.decode("utf-8").strip()
    logger.info(f"Created PR: {pr_url}")

    return pr_url


async def _run_git_command(
    repo_path: Path,
    args: list[str],
    env: dict[str, str] | None = None,
) -> tuple[str, str]:
    """Run a git command in the repository."""
    cmd = ["git"] + args

    default_env = {"PATH": "/usr/bin:/usr/local/bin"}
    if env:
        default_env.update(env)

    process = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        cwd=repo_path,
        env=default_env,
    )

    stdout, stderr = await process.communicate()

    if process.returncode != 0:
        error_msg = stderr.decode("utf-8", errors="replace")
        raise RuntimeError(f"Git command failed: {' '.join(args)}: {error_msg}")

    return stdout.decode("utf-8"), stderr.decode("utf-8")
